### ISSUE TITLE
[Documentation] Refactor usage and playground

### ISSUE THREAD

**Issue by YipingRuan** [vuetifyjs/vuetify#10257]
### Problem to solve
From https://github.com/vuetifyjs/vuetify/pull/9909

### Proposed solution
Use new style for playgrounds
Branch: https://github.com/vuetifyjs/vuetify/tree/docs/usages

## TODO:
- [x] Alerts
- [x] AppBars
- [x] Application
- [x] AspectRatios
- [x] Autocompletes
- [x] Avatars
- [x] Badges
- [x] Banners
- [x] BottomNavigation
- [x] BottomSheets
- [x] Breadcrumbs
- [x] ButtonGroups
- [x] Buttons
==================================== Yiping
- [x] Calendars
- [x] Cards
- [x] Carousels
- [ ] Categories
- [x] ChipGroups
- [x] Chips
- [x] ColorPickers
- [x] Combobox
- [x] DataIterators
- [ ] DataTables (Need help! Table head missing)
- [x] DatePickers
- [x] Dialogs
- [x] Dividers
- [x] ExpansionPanels
- [x] FileInputs
- [ ] FloatingActionButtons
- [x] Footer
- [ ] Forms (Need help! How to demo the value/lazy?)
- [ ] GridLists
- [ ] Grids (Need help! How to demo using the new usage?)
======================================== @sh7dm 
- [x] Hover
- [x] Icons
- [x] Images
- [x] Inputs @sh7dm 
- [ ] ItemGroups @sh7dm 
- [ ] Lazy @sh7dm 
- [ ] ListItemGroups @sh7dm 
- [ ] Lists @sh7dm 
- [ ] Menus @sh7dm 
- [ ] NavigationDrawers @sh7dm 
- [ ] OverflowBtns @sh7dm 
- [ ] Overlays @sh7dm 
- [ ] Paginations @sh7dm 
- [ ] Parallax @sh7dm 
======================================== Yiping
- [x] ProgressCircular
- [x] ProgressLinear
- [x] Ratings
- [ ] SelectionControls (Need help)
- [x] Selects
- [x] Sheets
- [x] SimpleTables
- [ ] SkeletonLoaders (Need help)
- [x] SlideGroups (Need help)
- [x] Sliders
- [x] Snackbars
- [x] Sparklines
========================================
- [x] Steppers
- [x] Subheaders
- [x] SystemBars
- [x] Tabs (How to add icons boolean?)
- [x] Textarea
- [ ] TextFields
- [ ] Timelines
- [ ] TimePickers
- [x] Toolbars
- [x] Tooltips
- [ ] Treeview
- [ ] Windows

**Comment by YipingRuan** [comment]
@sh7dm  let's finish this?
