### ISSUE TITLE
[Task] v-menu

### ISSUE THREAD

**Issue by chris-sab** [vuetifyjs/vuetify#13489]
# Overview

- Related Tasks: n/a
- Related Issues: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com). 

## TODO

- [x] `offset`
- [x] manual positioning
- [ ] `auto`
- [x] push
- [x] less buggy max sizing
- [x] activate on hover
- [x] close on content click
- [x] stack service
- [x] transitions
- [ ] `save()`
- [x] keyboard navigation of list items
- [x] keep open on hover when moving from activator to content

**Comment by jannis6023** [comment]
Hi, it seems like there is missing a function inside the activator slot to activate the menu.
I want it to activate @contextmenu.prevent but can't find a function for this!
