### ISSUE TITLE
[Task] Vuetify 3 Beta Release Checklist

### ISSUE THREAD

**Issue by johnleider** [vuetifyjs/vuetify#14729]
# Beta Release Checklist

The following is an in progress list of remaining tasks before we release beta. It will be updated daily; so watch for changes.

Discord, https://community.vuetifyjs.com/ and join channel **#v3-discussion**.

- [x] [`v-autocomplete`](https://github.com/vuetifyjs/vuetify/pull/14728)
- [x] [`v-carousel`](https://github.com/vuetifyjs/vuetify/pull/14813 )
- [x] [`v-combobox`](https://github.com/vuetifyjs/vuetify/pull/14791)
- [x] `v-tabs`
- [x] [`v-snackbar`](https://github.com/vuetifyjs/vuetify/pull/14789)
- [x] enable locale download and compilation in docs
- [x] update preset usage information
- [x] triage pending v3.0.0-alpha issues
- [x] review pending v3.0.0-alpha PRs
- [x] update issue generator

**Known Bugs**
- `v-app-bar` missing scrolling-techniques
- `v-text-field` with default density and outlined variant misaligned
- `v-list-item` (prepend/append slots)
- `v-system-bar` missing layout support

**Comment by robsontenorio** [comment]
Where can we check all components added since latest alpha?

**Comment by mrcego** [comment]
> Where can we check all components added since latest alpha?

https://app.zenhub.com/workspaces/vuetify-58dc72c478c79d245dc238f2/board?milestones=v3.0.0#2022-02-28

**Comment by HansCronau** [comment]
Since #14557 was closed in favour of this issue: is it too soon to update the dates on the [roadmap](https://next.vuetifyjs.com/en/introduction/roadmap)?

**Comment by sinisarudan** [comment]
seems that all the remaining components got checked :)

**Comment by robsontenorio** [comment]
@sinisarudan i don’t think so 😅

https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/index.ts

**Comment by sinisarudan** [comment]
Ah, I get it ...
You mean those that are commented on the link you've provided, like 
`// export * from './VBottomSheet'`
are the ones remaining to be supported, until Beta is out?

**Comment by robsontenorio** [comment]
Yes 🙌

**Comment by varHarrie** [comment]
Any plan for [transitions](https://next.vuetifyjs.com/en/styles/transitions/)?

**Comment by UkonnRa** [comment]
Any plan for unit testing doc with Vitest, [the testing tool recommanded by the official](https://vuejs.org/guide/scaling-up/testing.html#unit-testing)?

**Comment by sinisarudan** [comment]
Cheers! **Beta is officially LIVE!** :)
Beta: [Live](https://next.vuetifyjs.com/)
https://vuetifyjs.com/en/introduction/roadmap/#v3-0-titan
Target Release: May 2022

**Comment by guykatz** [comment]
Anyone knows what's the status of https://github.com/vuetifyjs/vuetify/issues/3435 ?
I thought data table virtualization will be a part of the beta already...

**Comment by AqingCyan** [comment]
May I ask, the document translation will be put after May, right？🥺

**Comment by johnleider** [comment]
> Anyone knows what's the status of #3435 ? I thought data table virtualization will be a part of the beta already... It carries the titan tag. Is it safe to assume the RC will include this?

It is our intent to include virtualization. @nekosaur would have to speak to development status.

> May I ask, the document translation will be put after May, right？🥺

Yes, once the documentation changes are to a state where it makes sense to have normal contributors, we will start to accept page translations. @MajesticPotatoe might have additional information on this as well.

**Comment by qSatan1s** [comment]
v-stepper-items
v-stepper-header
v-stepper-content
v-stepper

a small list of non-working comnets)

**Comment by UkonnRa** [comment]
Date Picker series, please.

**Comment by UkonnRa** [comment]
[VAutocomplete/VSelect] Hi, it seems that the code bases from `v3-beta.0` to `3.0.0-next-20220407.0` and the master branch do not match.

1. For `3.0.0-next-20220407.0`, there is no prop named itemText or itemValue, but DO in [the repo](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VSelect/VSelect.ts#L98)

   ![1-code-not-match](https://user-images.githubusercontent.com/16066720/162342026-1c85d271-6a26-4d44-8bd9-4d25e21bc638.png)

2. So, the behavior is not as expected as [the documentation](https://next.vuetifyjs.com/en/components/autocompletes/[](https://cdn.discordapp.com/attachments/361889521815519233/961789540081729556/1-code-not-match.png)) , customized item text/value is not working

   ![2-gen-item](https://user-images.githubusercontent.com/16066720/162342039-ec0f4e7d-6f01-4108-a78d-ef260e1129d0.png)


Anybody know what's happened? How can I use the correct v3 Vuetify?

**Comment by martinEtflais** [comment]
[VAutocomplete/VSelect] also it seems that update:modelValue event is triggered only upon removing from selection. model itself is updated correctly though (tested on both beta 0 and nightly build)

**Comment by craigrileyuk** [comment]
Is `v-sparklines` going to be a part of Vuetify 3?

Haven't seen it mentioned anywhere.

**Comment by hamzakm** [comment]
is Bidirectionality (LTR/RTL) going to be available?

**Comment by itsgifnotjiff** [comment]
Would the official release of Vuetify 3 include  `v-treeview` and the rest of the components available in 2.6.x?

**Comment by Rhilip** [comment]
I'm still waiting for `v-data-table`, will it available in next beta release?

**Comment by abumalekFayed** [comment]
where i can find current beta release number ?

**Comment by sinisarudan** [comment]
> where i can find current beta release number ?
You can find the latest version at https://github.com/vuetifyjs/vuetify/releases
Current one is **v3.0.0-beta.1**
