### ISSUE TITLE
[Documentation][META] components with missing prop/slot/... descriptions

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#18248]
- [x] [VCheckbox](https://vuetifyjs.com/en/api/v-checkbox/) (750b262)
- [x] [VCheckboxBtn](https://vuetifyjs.com/en/api/v-checkbox-btn/) (750b262)
- [x] [VChip](https://vuetifyjs.com/en/api/v-chip/) (e6131e7)
- [x] [VDataIterator](https://vuetifyjs.com/en/api/v-data-iterator/) (36f0e32)
- [x] [VDataTable](https://vuetifyjs.com/en/api/v-data-table/) (36f0e32)
- [x] [VDataTableFooter](https://vuetifyjs.com/en/api/v-data-table-footer/) (36f0e32)
- [x] [VDataTableRow](https://vuetifyjs.com/en/api/v-data-table-row/) (36f0e32)
- [x] [VDataTableRows](https://vuetifyjs.com/en/api/v-data-table-rows/) (36f0e32)
- [x] [VDataTableServer](https://vuetifyjs.com/en/api/v-data-table-server/) (36f0e32)
- [x] [VDataTableVirtual](https://vuetifyjs.com/en/api/v-data-table-virtual/) (36f0e32)
- [x] [VDatePicker](https://vuetifyjs.com/en/api/v-date-picker/)
- [x] [VDatePickerControls](https://vuetifyjs.com/en/api/v-date-picker-controls/)
- [x] [VDatePickerHeader](https://vuetifyjs.com/en/api/v-date-picker-header/)
- [x] [VDatePickerMonth](https://vuetifyjs.com/en/api/v-date-picker-month/)
- [x] [VDatePickerYears](https://vuetifyjs.com/en/api/v-date-picker-years/)
- [x] [VExpansionPanelTitle](https://vuetifyjs.com/en/api/v-expansion-panel-title/)
- [x] [VFileInput](https://vuetifyjs.com/en/api/v-file-input/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VImg](https://vuetifyjs.com/en/api/v-img/)
- [x] [VInput](https://vuetifyjs.com/en/api/v-input/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VLabel](https://vuetifyjs.com/en/api/v-label/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VLayout](https://vuetifyjs.com/en/api/v-layout/) (aa7d8db)
- [x] [VLayoutItem](https://vuetifyjs.com/en/api/v-layout-item/)
- [x] [VList](https://vuetifyjs.com/en/api/v-list/)
- [x] [VListGroup](https://vuetifyjs.com/en/api/v-list-group/)
- [x] [VListItem](https://vuetifyjs.com/en/api/v-list-item/)
- [x] [VListSubheader](https://vuetifyjs.com/en/api/v-list-subheader/)
- [x] [VLocaleProvider](https://vuetifyjs.com/en/api/v-locale-provider/)
- [x] [VMain](https://vuetifyjs.com/en/api/v-main/)
- [x] [VMenu](https://vuetifyjs.com/en/api/v-menu/)
- [x] [VNavigationDrawer](https://vuetifyjs.com/en/api/v-navigation-drawer/)
- [x] [VOtpInput](https://vuetifyjs.com/en/api/v-otp-input/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VOverlay](https://vuetifyjs.com/en/api/v-overlay/)
- [x] [VPagination](https://vuetifyjs.com/en/api/v-pagination/) (c1b5fc4)
- [x] [VParallax](https://vuetifyjs.com/en/api/v-parallax/)
- [x] [VPicker](https://vuetifyjs.com/en/api/v-picker/)
- [x] [VRadio](https://vuetifyjs.com/en/api/v-radio/)
- [x] [VRadioGroup](https://vuetifyjs.com/en/api/v-radio-group/)
- [x] [VRangeSlider](https://vuetifyjs.com/en/api/v-range-slider/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VRating](https://vuetifyjs.com/en/api/v-rating/)
- [x] [VResponsive](https://vuetifyjs.com/en/api/v-responsive/)
- [x] [VRow](https://vuetifyjs.com/en/api/v-row/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VSelectionControl](https://vuetifyjs.com/en/api/v-selection-control/)
- [x] [VSkeletonLoader](https://vuetifyjs.com/en/api/v-skeleton-loader/)
- [x] [VSlideGroup](https://vuetifyjs.com/en/api/v-slide-group/)
- [x] [VSlider](https://vuetifyjs.com/en/api/v-slider/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VSnackbar](https://vuetifyjs.com/en/api/v-snackbar/)
- [x] [VStepper](https://vuetifyjs.com/en/api/v-stepper/)
- [x] [VStepperActions](https://vuetifyjs.com/en/api/v--stepper-actions/)
- [x] [VStepperItem](https://vuetifyjs.com/en/api/v-stepper-item/)
- [x] [VSwitch](https://vuetifyjs.com/en/api/v-switch/)
- [x] [VTable](https://vuetifyjs.com/en/api/v-table/) (e3608a9)
- [x] [VTabs](https://vuetifyjs.com/en/api/v-tabs/) (a8a9f88)
- [x] [VTextarea](https://vuetifyjs.com/en/api/v-textarea/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VTextField](https://vuetifyjs.com/en/api/v-text-field/) (https://github.com/vuetifyjs/vuetify/pull/18302)
- [x] [VThemeProvider](https://vuetifyjs.com/en/api/v-theme-provider/)
- [x] [VTimeline](https://vuetifyjs.com/en/api/v-timeline/) (e3608a9)
- [x] [VTimelineItem](https://vuetifyjs.com/en/api/v-timeline-item/) (e3608a9)
- [x] [VTooltip](https://vuetifyjs.com/en/api/v-tooltip/) (e3608a9)
- [x] [VVirtualScroll](https://vuetifyjs.com/en/api/v-virtual-scroll/) (ceb5d8a)
- [x] [VWindow](https://vuetifyjs.com/en/api/v-window/) (e3608a9)
- [x] [VWindowItem](https://vuetifyjs.com/en/api/v-window-item/) (e3608a9)

**Comment by KaelWD** [comment]
Missing translations or missing prop descriptions?

**Comment by MajesticPotatoe** [comment]
Funny enough, started working on this last night.
