### ISSUE TITLE
Docs update master list

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuetifyjs/vuetify#7047]
# 📖Tasklist📖

Below is an list of the  features and functionality that Vuetify team is looking to implement in docs for Vuetify 2.0.

#### Why the changes in documentation?
Version 2 comes with a lot of changes to almost every component. Additionally, there are a lot of shortcomings to our current documentation behind the scenes that effect both users and maintainers, newbie and experts alike. As a part of the 2.0 release there is a lot of cleanup that can be done to help relieve some pain-points that have been plaguing our documentation and help us better maintain and sustain Vuetify.

#### How should I documentation bugs?
In most cases bugs can be reported via normal channels (Github) however depending on the content of the issue, it could be difficult determining the proper way to update. For a rule of thumb, until the release of 2.0, if the bug hits on any of the points in the road-map that has not been completed, we request you hold off on submitting an issue until after it has been complete. PR's are still welcome as they help further the completion of the tasks and will be reviewed/merged appropriately. These should utilize the `master` branch as we are now live with 2.0

#### How can I contribute?
If you are looking to help assist in these upgrades, please reach out to @MajesticPotatoe on our  [Discord channel](https://community.vuetifyjs.com) and he will get you started!

## Bug Reporting
- [ ] Improve issue creator to handle doc based issues
  - [x] Generate template for doc submission
  - [ ] Triage issues based on area effected (UI/UX, API, Examples, etc)

## Overall UI/UX/Experience
- [ ] Improve API Explorer and Component Discovery (TBD)
- [ ] Enable offline support (PWA) - #6174
  - [ ] Standard PWA install/cache
  - [ ] Ability to fully cache docs at install
  - [ ] Ability to receive PWA updates
- [ ] Improve Algolia search experience
- [ ] ~~Linking components to kitchen page~~ kitchen being deprecated or storybook
- [x] Dark mode
- [ ] Rework theme generator

### General Changes
- [ ] Better handle sub-component visibility (TBD)
- [x] Better organize accessibility to api/examples/usage - #7668
- [ ] Add mixins to docs
### API
- [ ] Refine API Generator
  - [x] ~~Breakout map files~~ - #6925
  - [ ] Auto generate slots/methods
  - [ ] Remove the need for map files all together
- [ ] Abstract API lang from general doc lang
- [ ] Mapping/Description housekeeping  - #7694 (in progress)
  - [ ] Add missing props/slots/methods
  - [ ] Cleanup deprecation/new-in tags
- [ ] Breakdown props based on inheritance
### Descriptions
- [ ] Comprehensive descriptions for each component
  - [ ] Describes proper use with usage examples
  - [ ] Details sub-components and their proper uses

## Informational Pages
- [ ] Improve clarity of step by steps

### Examples - #7074 (complete)
- [x] Playground example with output
- [x] Update examples for all components
  - [x] Internally categorize examples
    * simple/basic - examples displaying simplistic functions and prop based examples
    * intermediate - examples displaying customization or advance concepts like slots
    * complex - examples displaying in-depth or complete example prototyping (twitter cards, to-dos)
  - [x] Descriptions for each example
