### ISSUE TITLE
[Feature Request] Docs example upgrade master issue

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuetifyjs/vuetify#7074]
# 📖Tasklist📖

Below is an list components in which we doing a full on example upgrade. As a part of Vuetify 2.0 we would also like to take the time to enrich and clarify the user experience with our documentation through an overhaul of our component examples!

#### How can I contribute?
If you are looking to help assist in these upgrades, please reach out to @MajesticPotatoe on our  [Discord channel](https://community.vuetifyjs.com) and he will get you started!
If you understand the guidelines feel free to pick a component (check below to see if it is already being worked on so there is you don't waste time) and submit a PR to `next`.
An exemplar PR can be seen here: #7073

PR should include a tasklist that includes:
- [ ] Existing components are organized (simple/intermediate/complex)
- [ ] Examples are given descriptions that describe what they do. Exceptions and notable interactions are included with this description.
- [ ] Simple Examples
  - [ ] list out props here
- [ ] ~~Intermediate Examples~~ `NA` (use this format if not applicable)
  - [ ] list out props here
- [ ] Complex Examples
  - [ ] list out props here
- [ ] Usage Example + Description
- [ ] Playground Example

You can use this template: https://github.com/vuetifyjs/vuetify/projects/18#card-20797637

#### What does a completed item mean?
A completed item is one that has:

- examples organized by grouped structure
- a playground example
- a usage example
- at least 1 of each of the following (where applicable):
  - simple prop based examples
  - examples providing use of customization or advance concepts (slots, validation, function use)
  - examples displaying in-depth or complete example prototyping (twitter cards, todolist)

### Components
- [x] Alerts - #7073
- [x] AppBars - #7089
- [x] Autocompletes - #7348
- [x] Avatars - #7085
- [x] Badges - #7087 
- [x] Banners - #7093 
- [x] BottomNavigation - #7213
- [x] BottomSheets - #7349
- [x] Breadcrumbs - #7297 
- [x] ButtonGroups - #7082 
- [x] Buttons - #7082
- [x] Calendars - #7091
- [x] Cards - #7112 
- [x] Carousels - #7301
- [x] ChipGroups - #7120
- [x] Chips - #7163
- [x] Combobox - #7359
- [x] DataIterators - #7179
- [x] DataTables - #7650
- [x] DatePickers - #7364
- [x] Dialogs - #7278
- [x] Dividers - #7318 / #7343 
- [x] ExpansionPanels - #7370
- [x] FloatingActionButtons - #7082
- [x] Footer - #7371
- [x] Forms - #7447
- [x] Hover - #7414
- [x] Icons - #7190 
- [x] Images - #7228
- [x] Inputs - #7461
- [x] ItemGroups - #7380
- [x] ListItemGroups - #7646
- [x] Lists - #7423
- [x] Menus - #7402
- [x] NavigationDrawers - #7463
- [x] OverflowBtns - #7479
- [x] Overlays - #7469 
- [x] Paginations - #7522
- [x] Parallax - #7538
- [x] ProgressCircular - #7527
- [x] ProgressLinear - #7553
- [x] Ratings - #7526
- [x] SelectionControls - #7637
- [x] Selects - #7525
- [x] Sheets - #7176
- [x] SimpleTables - #7573  
- [x] SlideGroups - #7562
- [x] Sliders - #7506
- [x] Snackbars - #7488 
- [x] Sparklines - #7548
- [x] Steppers - #7545
- [x] Subheaders - #7346
- [x] SystemBars - #7569 
- [x] Tabs - #7581
- [x] Textarea  - #7633
- [x] TextFields - #7290
- [x] Timelines - #7505
- [x] TimePickers - #7564
- [x] Toolbars - #7635
- [x] Tooltips - #7081
- [x] Treeview - #7641 
- [x] Windows - #7397

**Comment by sh7dm** [comment]
# Template:

## Description
Update examples in prep for Vuetify 2.0

## Motivation and Context
More detail and clarity for use of component.

## TaskList:
The following should be complete before merging
- [ ] Existing components are organized (simple/intermediate/complex)
- [ ] Examples are given descriptions that describe what they do. Exceptions and notable interactions are included with this description.
- [ ] Simple Examples
  - [ ] name
- [ ] Intermediate Examples
  - [ ] name
- [ ] Complex Examples
  - [ ] name
- [ ] Usage Example + Description
- [ ] Playground Example

**Comment by MajesticPotatoe** [comment]
Complete! Thank you to all those who helped! Great work!
