### ISSUE TITLE
[Feature Request] Docs api upgrade master issue

### ISSUE THREAD

**Issue by MajesticPotatoe** [vuetifyjs/vuetify#7694]
# 📖Tasklist📖

As a part of Vuetify 2.0 we would also like to take the time to enrich and clarify the user experience with our documentation through an updating of our API! Below is an list components in which we are updating.

#### How can I contribute?
If you are looking to help assist in these upgrades, please reach out to @MajesticPotatoe on our  [Discord channel](https://community.vuetifyjs.com) and he will get you started!
If you understand the guidelines feel free to pick a component (check below to see if it is already being worked on so there is you don't waste time) and submit a PR to `next`.
An exemplar PR can be seen here: #7693

### Components
- [x] Alerts - #7693
- [x] AppBars - #7697
- [x] AspectRatios - #7747
- [x] Autocompletes - #7699
- [x] Avatars - #7702 
- [x] Badges - #7701
- [x] Banners - #7706
- [x] BottomNavigation - #7716
- [x] BottomSheets - #7710 
- [x] Breadcrumbs - #7717
- [x] ButtonGroups - #7721 
- [x] Buttons - #7722
- [x] Calendars - #7737 
- [x] Cards - no changes needed
- [x] Carousels - #7725
- [x] ChipGroups - #7731
- [x] Chips - #7732 
- [x] ColorPickers - no changes needed
- [x] Combobox - no changes needed
- [x] DataIterators - #7740
- [ ] DataTables - #7748 - needs sub components updated
- [x] DatePickers - #7923
- [x] Dialogs - #7712 
- [x] Dividers - #7695 
- [x] ExpansionPanels - #7778 
- [x] FloatingActionButtons - #8053
- [x] Footer - no changes needed
- [x] Forms - #8054 
- [ ] GridLists
- [ ] Grids
- [x] Hover - #7780
- [x] Icons - #7792
- [x] Images - #7801
- [x] Inputs - #7815 
- [x] ItemGroups - #7840
- [x] ListItemGroups - #7869
- [x] Lists - #7870
- [x] Menus - #7883
- [x] NavigationDrawers - #7886
- [x] OverflowBtns - #7892
- [x] Overlays - #7893
- [x] Paginations - #7892
- [x] Parallax - no changes needed
- [x] ProgressCircular - #7895
- [x] ProgressLinear - #7897
- [x] Ratings - #7898
- [x] Responsive - #7747 
- [x] SelectionControls - #8976
- [x] Selects - #7904
- [x] Sheets - no changes needed
- [x] SimpleTables - #8009
- [x] SlideGroups - #8012
- [x] Sliders - #7938
- [x] Snackbars - #7940
- [x] Sparklines - #7972
- [x] Steppers - #7975
- [x] Subheaders - #7982
- [x] SystemBars - #7983
- [x] Tabs - #7986
- [x] Textarea - #7993
- [x] TextFields - #7994
- [x] Timelines - #7902
- [x] TimePickers - #7923
- [x] Toolbars - #7739 
- [x] Tooltips - #7738 
- [x] Treeview - #7726 
- [x] Windows - #7734 

### Directives
- [ ] Resizing
- [ ] Ripples
- [ ] Scrolling
- [ ] TouchSupport

### Misc
- [ ] Internationalization
- [ ] Scroll
- [ ] Transitions

**Comment by MajesticPotatoe** [comment]
Example PR
# docs(component): api update for 2.0

## Description
Cleans and updates component api for Vuetify 2.0

## Motivation and Context
Keeping Vuetify up to date.

## TaskList:
The following should be complete before merging
- [x] Updated api generator maps (using source as reference)
    - [x] Add missing props/slots/events/public functions
    - [x] Remove unused props/slots/events
- [x] Update missing descriptions (en lang)
- [x] Spell check (good plugin for vscode is called code spell checker)
- [x] Organize props alphabetically (if you remember to)

**Comment by MajesticPotatoe** [comment]
Obsolete
